### ISSUE TITLE
[Bug] multiple accounts

### ISSUE THREAD

**Issue by mediaformat** [ShihabM/Mast#100]
Mast 1.6.6
From settings-> accounts, there is no way to add another account.

From the Instances/List menu, I can add another account, but the extra account avatar doesn’t show up there.
Also the timeline, activity and messages tabs show the proper account data, but not the profile page, it shows toots from an unknown user albeit the the avatar info of my first account.

**Comment by ShihabM** [comment]
Fixed for 1.7.0
