### ISSUE TITLE
Boost / Favorite button states

### ISSUE THREAD

**Issue by mediaformat** [ShihabM/Mast#15]
2 issues, related

- bug: boosting a toot that I had already boosted gives an “unboosted” message. However re-tapping the boost icon continues to “unboost”, or at least keeps giving the same message.

- Feature: add a visual representation of state of boost and favorite actions, so user would see if they are about to boost or unboost.

**Comment by ShihabM** [comment]
Thanks for this, will aim to fix this for a future update.

**Comment by ShihabM** [comment]
Added.
