### ISSUE TITLE
Timeline does not get updated

### ISSUE THREAD

**Issue by myhubacct** [ShihabM/Mast#30]
Have tried to swipe down the home and local timeline to refresh the toot list. It results in a arrow sign, which in the past indicated that it is already up to date. Have checked it via the web interface which showed me more recent content.

steps to reproduce:
- ensure there is newer content than the mast time lines is showing
- swipe down the local or home time line
- result: arrow symbol will be shown for a short while on top of the time line

expected result
- updated toot list with indicator of how many toots since last refresh are loaded

environment:
iPhone 6
iOS 12.1
Mast 1.2.4

**Comment by ShihabM** [comment]
Fixed.
