### ISSUE TITLE
[Feature request] Pull down to load toots in List view

### ISSUE THREAD

**Issue by mediaformat** [ShihabM/Mast#42]
Not sure if it’s a bug, or the way the feature is intended...

Users added to a list are removed from main timeline. 

My expectation was that it would be more like a filter. Showing exclusively what was in the list, but not removing it from the timeline.

If this is the intended behaviour, it would be useful to add the refresh action inside the list.

**Comment by mediaformat** [comment]
Not sure if it was an issue with 1.4.4, but the list behviour seems normal now (users in lists also showing in main timline).

It would be nice to have the pulldown to load toots from within the lists.

**Comment by ShihabM** [comment]
Fixed.
