### ISSUE TITLE
[Feature request] Remove fav, boost popups

### ISSUE THREAD

**Issue by VyrCossont** [ShihabM/Mast#66]
When I'm viewing an individual toot and fav or boost it, a greyish rounded-rect popup appears briefly saying that i faved or boosted it. This prevents rapid double-tapping (faving & boosting the same toot), and is redundant with the fav or boost button changing state, as well as with confetti if the user has that turned on. Also, it doesn't match the theme: it's always white on grey.

**Comment by VyrCossont** [comment]
Examples (also noticed this behavior when tooting):

![demo boost](https://user-images.githubusercontent.com/26195552/51816419-568e5100-227b-11e9-9b3d-6f7e598da5e5.png)
![demo fav](https://user-images.githubusercontent.com/26195552/51816420-568e5100-227b-11e9-9de6-ea03c79b9814.png)
![demo toot](https://user-images.githubusercontent.com/26195552/51816421-568e5100-227b-11e9-801e-0d7955c48a8c.png)

**Comment by ShihabM** [comment]
Thanks for this, will add the option later.

**Comment by ShihabM** [comment]
Added.
