### ISSUE TITLE
[Bug] Using multiple accounts, toots from accounts I don’t follow still show up in home timeline

### ISSUE THREAD

**Issue by SomniusTiger** [ShihabM/Mast#70]
I am signed in to two accounts. After switching from my first account to my second account and tapping the “load more” button a few times, toots from accounts I do not follow from my second account (but I do follow on my first) are showing up in my home timeline.

This error is occurring on my iPhone XS, using iOS 12.1.3, on Mast 1.5.0.

**Comment by ShihabM** [comment]
Will look into this.

**Comment by ShihabM** [comment]
Fixed for 1.7.0
