### ISSUE TITLE
[Bug] Duplicate Id’s when replying to posts 

### ISSUE THREAD

**Issue by mcg** [ShihabM/Mast#72]
I believe this only happens with Pleroma, but when you reply to a post it duplicates the OP in the reply field.  See attached. 
![374579af-7db7-491d-b542-f1b4027a286a](https://user-images.githubusercontent.com/305/52507912-e9ef4c80-2bc0-11e9-8f73-7115f5a85b56.png)

**Comment by ShihabM** [comment]
Thanks, will fix this for the next version.

**Comment by mcg** [comment]
This seems fixed
