### ISSUE TITLE
App keeps crashing with new Thumb Scoller

### ISSUE THREAD

**Issue by pbeckmann** [ShihabM/Mast#75]
Hello,

i am using the App on the iPad Pro 11“ (2018) with 256GB storage and wifi-only.

I wanted to try the new thumb scroll, but unfortunately after activating the option and a forced restart of the app, the app crashes instantly. An reset over the settings app didn’t work too, after the reinstall the app worked again. After inserting my account and reactivating the option and a restart the app crashed instantly again.

Unfortunately i don’t own a Mac and i don’t have any experience developing ios apps, i don’t know how to provide the logs.

But i would be happy to test anything.

**Comment by ShihabM** [comment]
Thanks for letting me know, I shall give this a look and attempt to fix it soon.

**Comment by ShihabM** [comment]
Fixed.
