### ISSUE TITLE
Support Polls

### ISSUE THREAD

**Issue by mcg** [ShihabM/Mast#78]
Polls were just added to Mastodon. It would be awesome to fully support them but right now they crash Mast.

**Comment by wakest** [comment]
you could be the first app to support them if you wanted to be! actually even before mastodon.social web interface cause they were added to the api already but there's just no interface to create them yet..

**Comment by ShihabM** [comment]
@mcg @wakest This is currently being worked on, and both viewing/posting support should be coming to Mast sometime this week.

**Comment by ShihabM** [comment]
Added.
