### ISSUE TITLE
[Bug] Follow Button on Profile Page broken

### ISSUE THREAD

**Issue by rstockm** [ShihabM/Mast#84]
Mast 1.6.0 - the follow-button on the profile Page (on the left of the profile Image) doesn't work.

**Comment by ShihabM** [comment]
Will check, thanks. What device are you using?

**Comment by rstockm** [comment]
iPhone 8, latest iOS Release.

**Comment by rstockm** [comment]
This is still an issue in 1.6.4

**Comment by ShihabM** [comment]
Fixed for 1.7.0
