### ISSUE TITLE
[Enhancement] Progress Indicator

### ISSUE THREAD

**Issue by rstockm** [ShihabM/Mast#85]
The Progress Indicator feels weird.
- ist starts as an arrowwhich turns direction (ok)
- it becomes a vertical line (why?)
- for a split-second it becomes a circle
- finally it becomes a checkmark 

And it's quite tiny.

Suggestion: just use the arow and the circle.

**Comment by ShihabM** [comment]
Will change this in the next update.

**Comment by ShihabM** [comment]
Fixed for 1.7.0
