### ISSUE TITLE
[Enhancement] integrity and sync of displayed data

### ISSUE THREAD

**Issue by rstockm** [ShihabM/Mast#86]
This is a fuzzy one.
Mast 1.6.0 - I experience inconsistencies between different views.
a) I get a push notification with new @mentiones
b) Istart Mast an go to the Activity view. The new messages don't show up.
c) I pull-reload the page and new messages appear.
d) I swith to the home-view and the new messages don't show up.
e) I pull-reload and the new messeages show up.

Stable and fast WiFi.
I do niot experience this kind of behaviour in other mastodon apps, so it's not a problem of my instance.

**Comment by ShihabM** [comment]
This is odd, will investigate.

**Comment by rstockm** [comment]
Frankly speaking this is my only concern, the other issues are just "nice to have".
It feels like caching is broken, too. Loading a 3 messages conversation in the new Direct Messages View takes up to 10 (!) seconds (on a fast WiFi and a lightning fast Mastodon server).
After a while it get's better, but if I shut down the app and restart it's all back to square one.

I can upload some screen capture vids if it helps.

**Comment by ShihabM** [comment]
I've worked on fixing this for the next update, so DMs will load much quicker now and not go through that slow process.

**Comment by rstockm** [comment]
In general every (?) boost/fav counter seems out of sync. Everytime I fav and boost I have to reload the view to get the counter right. 

Expected behaviour: always show/refresh the actual numbers in realtime

**Comment by ShihabM** [comment]
Fixed for 1.7.0
