### ISSUE TITLE
[Bug] Settings: Default Mentions Tab

### ISSUE THREAD

**Issue by rstockm** [ShihabM/Mast#89]
![77781A4B-92EE-4375-BB5A-BF94CE5EAD4E](https://user-images.githubusercontent.com/3195116/55667137-b3e4e680-5858-11e9-8a23-a5481a796eca.jpeg)
If I switch the setting to „Activity“ the tab highlighting is broken. If I switch the tap, the App crashs.

**Comment by ShihabM** [comment]
Fixed for 1.7.0
