### ISSUE TITLE
[Bug] Missing poll indicator in toots I've boosted

### ISSUE THREAD

**Issue by jumoru** [ShihabM/Mast#94]
When I've boosted a toot that has a poll then there's no poll indicator

![IMG_4390](https://user-images.githubusercontent.com/27491477/56747325-093c5580-677e-11e9-85d3-eefe50e6a483.jpg)

However, when someone else boosts a toot with a poll, the poll indicator is visible

![IMG_4391](https://user-images.githubusercontent.com/27491477/56747391-2cff9b80-677e-11e9-88f1-deb8fef8b08e.jpg)

**Comment by ShihabM** [comment]
Fixed for 1.7.0
