### ISSUE TITLE
DM tab treats mentions weirdly

### ISSUE THREAD

**Issue by trwnh** [ShihabM/Mast#98]
I assume that there's some code trying to strip out the mention from DMs, but:
- [ ] it only seems to work on messages that are not your own
- [ ] sometimes it leaves the `@domain.tld` part unremoved
- [ ] it doesn't remove mentions of other people, so it looks weird that mentions of you are missing, as if you're not part of the conversation

**Comment by ShihabM** [comment]
Fixed for 1.7.0
