### ISSUE TITLE
DM text after emojo is unthemed

### ISSUE THREAD

**Issue by trwnh** [ShihabM/Mast#99]
On a dark theme, when receiving a DM with emojo in it, all text after that first emojo is unthemed.

Sample DM might look like this:
`@you this part is in white text :emojo: but this part is in black text`

This makes the latter parts unreadable since they are black-on-dark-grey.

This happens in the `@You` tab of notifications, as well as the list of DMs in the `Direct Messages` tab.

**Comment by ShihabM** [comment]
Fixed.
